# Generated by Django 5.0.6 on 2024-06-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('ClassName', models.CharField(max_length=100, null=True)),
                ('Subject', models.CharField(max_length=50, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ClassCode', models.CharField(max_length=6, null=True, verbose_name='Class Code')),
                ('ClassJoinCode', models.CharField(max_length=6, null=True, verbose_name='join Code')),
            ],
        ),
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.BigIntegerField(null=True, verbose_name='UserID')),
                ('ClassID', models.BigIntegerField(null=True, verbose_name='ClassID')),
                ('Teacher', models.BooleanField(null=True, verbose_name='IsTeacher')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Name', models.CharField(max_length=100, null=True)),
                ('UserName', models.CharField(max_length=100, null=True)),
                ('join_date', models.DateField(null=True, verbose_name='Date Joined')),
                ('IsTeacher', models.BooleanField(null=True, verbose_name='Is Teacher')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
