# Generated by Django 5.0.6 on 2024-06-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='account',
            name='join_date',
        ),
        migrations.AlterField(
            model_name='account',
            name='IsTeacher',
            field=models.BooleanField(default=False, verbose_name='Is Teacher'),
        ),
    ]
