# Generated by Django 5.0.6 on 2024-06-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_user_remove_account_join_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Grade',
            field=models.IntegerField(default=0, verbose_name='Grade'),
        ),
    ]
