# Generated by Django 5.0.6 on 2024-06-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Grade',
            field=models.IntegerField(null=True, verbose_name='Grade'),
        ),
    ]
