# Generated by Django 5.0.6 on 2024-06-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='ClassJoinCode',
            field=models.CharField(max_length=6, null=True, unique=True, verbose_name='join Code'),
        ),
    ]
