# Generated by Django 5.0.6 on 2024-06-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_classes_classjoincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='ClassID',
            field=models.BigIntegerField(verbose_name='ClassID'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='UserID',
            field=models.BigIntegerField(verbose_name='UserID'),
        ),
    ]
