# Generated by Django 5.0.6 on 2024-06-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_classlist_classid_alter_classlist_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='Teacher',
            field=models.BooleanField(default=False, verbose_name='IsTeacher'),
            preserve_default=False,
        ),
    ]
