# Generated by Django 5.0.6 on 2024-06-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_classlist_classcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='ClassCode',
            field=models.CharField(max_length=6, verbose_name='Class Code'),
        ),
    ]
