# Generated by Django 5.0.6 on 2024-06-20 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_classlist_classcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlist',
            name='ClassCode',
        ),
    ]
