# Generated by Django 5.0.6 on 2024-06-20 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_classlist_classcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='ClassID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.classes'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
    ]
