# Generated by Django 5.0.6 on 2024-07-05 00:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_classlist_classid_alter_classlist_userid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="classes",
            name="Teachers",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
