# Generated by Django 5.0.6 on 2024-07-05 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_classes_teachers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subjects",
            fields=[
                ("SubjectName", models.CharField(max_length=50)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "HeadTeacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.account",
                    ),
                ),
            ],
        ),
    ]
