# Generated by Django 5.0.6 on 2024-07-05 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_subjects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classes",
            name="Subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounts.subjects"
            ),
        ),
    ]
