# Generated by Django 5.0.6 on 2024-06-20 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0001_initial'),
        ('accounts', '0005_alter_account_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenthelp',
            name='classCode',
        ),
        migrations.RemoveField(
            model_name='studenthelp',
            name='user',
        ),
        migrations.AddField(
            model_name='studenthelp',
            name='classCode',
            field=models.ManyToManyField(to='accounts.classes'),
        ),
        migrations.AddField(
            model_name='studenthelp',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
