# Generated by Django 5.0.6 on 2024-06-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0003_studenthelp_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenthelp',
            old_name='classCode',
            new_name='classid',
        ),
        migrations.AlterField(
            model_name='studenthelp',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date posted'),
        ),
    ]
