# Generated by Django 5.0.6 on 2024-06-21 00:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0004_rename_classcode_studenthelp_classid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datelogged', models.DateTimeField(auto_now_add=True, verbose_name='Date Logged')),
                ('userAction', models.CharField(choices=[('JOIN_CLASS_REQUEST', 'join class request'), ('CREATE_HELP_LOG_REQUEST', 'create help log requet')], max_length=50)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
