# Generated by Django 5.0.6 on 2024-06-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0005_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='details',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
