# Generated by Django 5.0.6 on 2024-06-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0006_log_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='datelogged',
            field=models.DateTimeField(verbose_name='Date Logged'),
        ),
    ]
