# Generated by Django 5.0.6 on 2024-06-21 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0007_alter_log_datelogged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='datelogged',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 11, 37, 49, 438643), verbose_name='Date Logged'),
        ),
    ]
