# Generated by Django 5.0.6 on 2024-06-21 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0021_alter_log_datelogged_alter_studenthelplog_datelogged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='datelogged',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 14, 35, 18, 506836, tzinfo=datetime.timezone.utc), verbose_name='Date Logged'),
        ),
        migrations.AlterField(
            model_name='studenthelplog',
            name='datelogged',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 14, 35, 18, 508038, tzinfo=datetime.timezone.utc), verbose_name='Date Logged'),
        ),
    ]
