# Generated by Django 5.0.6 on 2024-06-21 04:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0023_alter_log_datelogged_alter_studenthelplog_datelogged'),
        ('accounts', '0012_alter_classlist_classid_alter_classlist_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenthelplog',
            name='details',
        ),
        migrations.AddField(
            model_name='studenthelplog',
            name='reason',
            field=models.CharField(choices=[('HAND_UP', 'hand_up'), ('toilet', 'toilet'), ('WATER', 'water')], default='water', max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='datelogged',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 14, 37, 6, 331905, tzinfo=datetime.timezone.utc), verbose_name='Date Logged'),
        ),
        migrations.AlterField(
            model_name='studenthelplog',
            name='datelogged',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 14, 37, 6, 333131, tzinfo=datetime.timezone.utc), verbose_name='Date Logged'),
        ),
        migrations.AlterField(
            model_name='studenthelplog',
            name='userAction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.classes'),
        ),
    ]
