# Generated by Django 5.0.6 on 2024-06-21 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0024_remove_studenthelplog_details_studenthelplog_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='datelogged',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 15, 1, 21, 832055, tzinfo=datetime.timezone.utc), verbose_name='Date Logged'),
        ),
        migrations.AlterField(
            model_name='studenthelplog',
            name='datelogged',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 15, 1, 21, 833266, tzinfo=datetime.timezone.utc), verbose_name='Date Logged'),
        ),
    ]
