# Generated by Django 5.0.6 on 2024-06-23 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0025_alter_log_datelogged_alter_studenthelplog_datelogged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenthelplog',
            old_name='userAction',
            new_name='classid',
        ),
        migrations.AlterField(
            model_name='log',
            name='datelogged',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 24, 9, 5, 2, 214029, tzinfo=datetime.timezone.utc), verbose_name='Date Logged'),
        ),
        migrations.AlterField(
            model_name='studenthelplog',
            name='datelogged',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 24, 9, 5, 2, 215305, tzinfo=datetime.timezone.utc), verbose_name='Date Logged'),
        ),
    ]
