# Generated by Django 5.0.6 on 2024-06-23 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0029_rename_classid_studenthelplog_useraction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenthelplog',
            old_name='userAction',
            new_name='classes',
        ),
        migrations.AlterField(
            model_name='log',
            name='datelogged',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 24, 9, 7, 44, 473827, tzinfo=datetime.timezone.utc), verbose_name='Date Logged'),
        ),
        migrations.AlterField(
            model_name='studenthelplog',
            name='datelogged',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 24, 9, 7, 44, 475072, tzinfo=datetime.timezone.utc), verbose_name='Date Logged'),
        ),
    ]
