# Generated by Django 5.0.6 on 2024-06-24 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSupport', '0030_rename_useraction_studenthelplog_classes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='datelogged',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 25, 9, 22, 20, 983619, tzinfo=datetime.timezone.utc), verbose_name='Date Logged'),
        ),
        migrations.AlterField(
            model_name='studenthelplog',
            name='datelogged',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 25, 9, 22, 20, 985207, tzinfo=datetime.timezone.utc), verbose_name='Date Logged'),
        ),
    ]
