# Generated by Django 5.0.6 on 2024-07-05 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StudentSupport", "0031_alter_log_datelogged_alter_studenthelplog_datelogged"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="datelogged",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 5, 10, 10, 1, 94886, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date Logged",
            ),
        ),
        migrations.AlterField(
            model_name="studenthelp",
            name="reason",
            field=models.CharField(
                choices=[
                    ("HAND_UP", "hand_up"),
                    ("TOILET", "toilet"),
                    ("WATER", "water"),
                ],
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="studenthelplog",
            name="datelogged",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 5, 10, 10, 1, 96617, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date Logged",
            ),
        ),
        migrations.AlterField(
            model_name="studenthelplog",
            name="reason",
            field=models.CharField(
                choices=[
                    ("HAND_UP", "hand_up"),
                    ("TOILET", "toilet"),
                    ("WATER", "water"),
                ],
                max_length=9,
            ),
        ),
    ]
