# Generated by Django 5.0.6 on 2024-07-05 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "StudentSupport",
            "0032_alter_log_datelogged_alter_studenthelp_reason_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="datelogged",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 5, 13, 39, 57, 324206, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date Logged",
            ),
        ),
        migrations.AlterField(
            model_name="studenthelplog",
            name="datelogged",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 5, 13, 39, 57, 325993, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date Logged",
            ),
        ),
    ]
