# Generated by Django 5.0.6 on 2024-07-05 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StudentSupport", "0033_alter_log_datelogged_alter_studenthelplog_datelogged"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="datelogged",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 5, 13, 50, 2, 566647, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date Logged",
            ),
        ),
        migrations.AlterField(
            model_name="studenthelplog",
            name="datelogged",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 5, 13, 50, 2, 569372, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date Logged",
            ),
        ),
    ]
