# Generated by Django 5.0.6 on 2024-07-05 05:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StudentSupport", "0035_alter_log_datelogged_alter_studenthelplog_datelogged"),
        ("accounts", "0015_alter_classes_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="datelogged",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 5, 15, 5, 55, 816653, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date Logged",
            ),
        ),
        migrations.RemoveField(
            model_name="studenthelp",
            name="classid",
        ),
        migrations.AlterField(
            model_name="studenthelplog",
            name="datelogged",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 5, 15, 5, 55, 817902, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date Logged",
            ),
        ),
        migrations.AddField(
            model_name="studenthelp",
            name="classid",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.classes",
            ),
            preserve_default=False,
        ),
    ]
