# Generated by Django 5.0.6 on 2024-07-05 05:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "StudentSupport",
            "0036_alter_log_datelogged_remove_studenthelp_classid_and_more",
        ),
        ("accounts", "0015_alter_classes_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="datelogged",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 5, 15, 21, 9, 1856, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date Logged",
            ),
        ),
        migrations.RemoveField(
            model_name="studenthelp",
            name="user",
        ),
        migrations.AlterField(
            model_name="studenthelplog",
            name="datelogged",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 5, 15, 21, 9, 2670, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date Logged",
            ),
        ),
        migrations.AddField(
            model_name="studenthelp",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.account",
            ),
            preserve_default=False,
        ),
    ]
